export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'

export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const GET_USERS = 'GET_USERS'
export const USER_LOADING = 'USER_LOADING'
export const GET_USERS_FAIL = 'USERS_FAIL'
export const GET_USER = 'GET_USER'
export const GET_USER_FAIL = 'USER_FAIL'
export const DELETE_USER = 'DELETE_USER'
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL'
